apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: ebs-demo

spec:
  serviceName: nginx
  replicas: 2

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:latest

          ports:
            - containerPort: 80

          volumeMounts:
            - name: nginx-data
              mountPath: /usr/share/nginx/html

  volumeClaimTemplates:
    - metadata:
        name: nginx-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: ebs-sc

        resources:
          requests:
            storage: 10Gi